apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-service
spec:
  selector:
    matchLabels:
      app: photo-service
  template:
    metadata:
      labels:
        app: photo-service
    spec:
      containers:
      - name: photo-service
        image: jaewoozzang/photo_service:v0.93
        ports:
        - containerPort: 5003
        volumeMounts:
        - name: photo-storage
          mountPath: /app/static/uploads
      volumes:
      - name: photo-storage
        persistentVolumeClaim:
          claimName: photo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: photo-service
spec:
  ports:
    - port: 5003
  selector:
    app: photo-service